Empirical distributions quantiles
tensorflow/probability pull request #1550
Opened 2022-04-12 18:48 UTC by ltsaprounis

Fixes #1549

Implemented the quantile method for the Empirical distribution class by interfacing the `tfp.stats.percentile` method and scaling the input appropriately. I think that the tests pass locally. I've tested using the command below: 
`bazel test -c opt tensorflow_probability/python/distributions:normal_test \
    --test_arg=--test_regex=EmpiricalScalarTest`

Let me know if I need to add more tests in the `EmpiricalNdTest` and the `EmpiricalVectorTest` classes. 

Thanks!

2022-05-03 20:49 UTC, SiegeLordEx requested changes
Thanks for the change. Sorry for the delay, some weird issue with the CLA bot not telling us that the CLA was signed. I left a few comments.

2022-05-03 20:49 UTC, SiegeLordEx commented on tensorflow_probability/python/distributions/empirical.py
> +from tensorflow_probability.python.stats import percentile
Our style guide forbids us from importing functions directly, so this should just import stats and then later on the call should be `stats.percentile`

2022-05-03 20:49 UTC, SiegeLordEx commented on tensorflow_probability/python/distributions/empirical.py
> +    if value > 1 or value < 0:
You don't need to do this check here, it's already handled by the base Distribution class.

2022-05-07 20:21 UTC, ltsaprounis commented
> Thanks for the change. Sorry for the delay, some weird issue with the CLA bot not telling us that the CLA was signed. I left a few comments.

Thanks for the review! I addressed all the requested changes and the [linting checks](https://github.com/tensorflow/probability/blob/main/CONTRIBUTING.md#helper-scripts)  from the CONTRIBUTING.md now pass locally.

2022-05-09 20:27 UTC, SiegeLordEx approved these changes

2022-05-09 20:27 UTC, SiegeLordEx commented
Thanks! I'll send this along to our internal review system and we'll get this merged once that is done.

2022-05-11 21:43 UTC, ltsaprounis commented
According to the [CI logs](https://github.com/tensorflow/probability/runs/6359160764?check_suite_focus=true#step:4:1860) the test I wrote for the quantiles `test_empirical_quantiles` is failing and the following error is raised: 
`AttributeError: module 'tensorflow_probability.python.internal.backend.numpy.v2' has no attribute 'bfloat16'`

@SiegeLordEx - Do you have any idea what this means? I'm a bit stuck on this...

2022-05-13 19:31 UTC, SiegeLordEx commented
The percentile function is erroneously exposed by the numpy backend. What I'll do is just disable the test and the quantile implementation under numpy.

2022-05-13 20:18 UTC, merged

2022-05-24 21:50 UTC, ltsaprounis commented
@SiegeLordEx - thanks for merging this! 

> The percentile function is erroneously exposed by the numpy backend. What I'll do is just disable the test and the quantile implementation under numpy.

Any idea why this happens? 
Apologies if this sounds naive, I'm not that familiar with the backend of tensorflow probability, but numpy has a percentile function of it's own, is there a way to resolve this by replacing the percentile function with the native numpy function?

2022-05-24 22:39 UTC, SiegeLordEx commented
TFP has its own [percentile function implementation](https://github.com/tensorflow/probability/blob/main/tensorflow_probability/python/stats/quantiles.py#L428) which supports batching and (outside of numpy, were it to work) gradients.

Currently the module where the TFP's percentile is defined is erroneously exposed under the numpy backend. This is because of a misconfiguration of the [bazel target](https://github.com/tensorflow/probability/blob/main/tensorflow_probability/python/stats/BUILD#L157), which should ideally indicate that it doesn't work under numpy. Unfortunately it's tricky to fix, since there's a bit of a cascading set of changes that would need to be made to change just that one target. We haven't had the time to do that.